# ---------- BUILD STAGE ----------
FROM maven:3.9-eclipse-temurin-17-alpine AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn -DskipTests clean package

# ---------- RUNTIME STAGE ----------
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/target/recipe-app.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]
