server.port=8080
spring.application.name=recipe-app

# ?? ????????? H2 (?????? ????????)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:recipes;DB_CLOSE_DELAY=-1}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
